// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hdcindihrbynganwrgum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkY2luZGlocmJ5bmdhbndyZ3VtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NjI4MDEsImV4cCI6MjA3MzQzODgwMX0.0-5z_-3pazyKDhJM7mGJoMCxQz9JL1V9j9sVcgfaV_Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});